name: Automatically merge PRs
author: erbridge
description:
  Automatically merge PRs where intent to merge is shown once all required
  checks pass
inputs:
  automerge-labels:
    description:
      a comma-separated list of labels to automatically merge without any other
      indication of intent (if allowed by branch protection rules)
    required: false
  repo-token:
    description:
      a personal access token with at least write permission to the repository
    required: true
  strict:
    description: whether to fail when running in an invalid context or not
    required: false
    default: "true"
runs:
  using: node12
  main: dist/index.js
branding:
  icon: git-pull-request
  color: purple
