name: Automatically merge PRs
author: erbridge
description:
  Automatically merge PRs where intent to merge is shown and all required checks
  are currently passing, by rebasing and waiting for required checks if needed,
  and merging
runs:
  using: node12
  main: dist/index.js
branding:
  icon: git-pull-request
  color: purple
