name: Automatically merge PRs
author: erbridge
description:
  Automatically merge PRs where intent to merge is shown once all required
  checks pass
inputs:
  repo-token:
    description:
      a personal access token with at least write permission to the repository
    required: true
  strict:
    description: whether to fail when running in an invalid context or not
    required: false
    default: true
runs:
  using: node14
  main: dist/index.js
branding:
  icon: git-pull-request
  color: purple
